website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func




class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user
from . import db
import json
import pickle
import numpy as np
views = Blueprint('views', __name__)


def predict(values):
   # if len(values) == 10:
   print(len(values))
   model = pickle.load(open("chronic.pkl", "rb"))
   values = np.asarray(values)
   print(values)
   return model.predict(values.reshape(1, -1))[0]

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    return render_template("home.html", user=current_user)

@views.route("/kidney", methods=['POST','GET'])
@login_required
def kidney():
    return render_template('kidney.html',user=current_user)

@views.route("/predict", methods = ['POST', 'GET'])
#@login_required
def predictPage():
    
    if request.method == 'POST':
            to_predict_dict = request.form.to_dict()
            print(to_predict_dict)
            to_predict_list = list(map(float, list(to_predict_dict.values())))
            print(to_predict_list,len(to_predict_list))
            pred = predict(to_predict_list)
    else:
        flash( "Please enter valid Data", category='error')
        return render_template("home.html",user=current_user)
  

    return render_template('predict.html',user=current_user, pred = pred)




website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link
    rel="stylesheet"
    href="static\css\styles.css"
    />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon">
            </span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" id="home" href="/">Home</a>
                <a class="nav-item nav-link" id="home" href="/kidney">Chronic Kidney Disease Predictor </a>
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                {% else  %}
                <a class="nav-item nav-link" id="login" href="/login">Login</a>
                <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
               {% endif %}
            </div>
        </div>
    </nav>
    {% with messages=get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category,message in messages %}
    {% if category=='error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
  <script
  type="text/javascript"
  src="{{ url_for('static', filename='index.js') }}"
></script>
</body>
</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block content %}
{% if message %}
        <div class="alert alert-danger">{{ message }}</div>
    {% endif %}


    
    <main role="main">
      <section class="jumbotron border-top p-3 p-md-5 text-white rounded bg-dark text-center " >
        <div class="container">
          <h1 class="jumbotron-heading">Chronic Kidney Disease Prediction</h1>
          <p class="lead"> Kidney disease (KD) is one of the most
critical health problems due to its increasing prevalence. In this
paper, we aim to test the ability of machine learning algorithms
for the prediction of chronic kidney disease using the smallest
subset of features</p>
          <p>
            <a href="https://www.mayoclinic.org/diseases-conditions/chronic-kidney-disease/symptoms-causes/syc-20354521" class="btn btn-primary my-2">Read More about the Disease</a>
          </p>
        </div>
      </section>
    
      <div class="row gx-4 gx-lg-5">
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">What causes CKD?</h2>
                    <p class="card-text">The two main causes of chronic kidney disease are diabetes and high blood pressure, which are responsible for up to two-thirds of the cases. Diabetes happens when your blood sugar is too high, causing damage to many organs in your body, including the kidneys and heart, as well as blood vessels, nerves and eyes. High blood pressure, or hypertension, occurs when the pressure of your blood against the walls of your blood vessels increases. If uncontrolled, or poorly controlled, high blood pressure can be a leading cause of heart attacks, strokes and chronic kidney disease. Also, chronic kidney disease can cause high blood pressure.</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">What are the symptoms of CKD?</h2>
                    <p class="card-text">The two main causes of chronic kidney disease are diabetes and high blood pressure, which are responsible for up to two-thirds of the cases. Diabetes happens when your blood sugar is too high, causing damage to many organs in your body, including the kidneys and heart, as well as blood vessels, nerves and eyes. High blood pressure, or hypertension, occurs when the pressure of your blood against the walls of your blood vessels increases. If uncontrolled, or poorly controlled, high blood pressure can be a leading cause of heart attacks, strokes and chronic kidney disease. Also, chronic kidney disease can cause high blood pressure.</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">Facts about Chronic Kidney Disease</h2>
                    <p class="card-text">37 million American adults have CKD and millions of others are at increased risk.
                        Early detection can help prevent the progression of kidney disease to kidney failure.
                        Heart disease is the major cause of death for all people with CKD.
                        Glomerular filtration rate (GFR) is the best estimate of kidney function.
                        Hypertension causes CKD and CKD causes hypertension.
                        Persistent proteinuria (protein in the urine) means CKD is present.
                        High risk groups include those with diabetes, hypertension and family history of kidney failure.</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
            </div>
        </div>
</div>


 <!-- Footer-->
 <footer class="py-5 bg-dark">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
</footer>
</main>

    


{% endblock %}

website/templates/kidney.html
{% extends 'base.html' %}  {% block title %}Chronic Kidney Disease Predictor {% endblock %}
{% block content %}

<div class="row " >
   
    <div class="col-md-12">
        <center><h1>Kidney Disease Predictor</h1></center>
        <div class="card card-body" style="border: 1px solid black;">
            <form class="form-horizontal"  action="{{ url_for('views.predictPage') }}"  method="POST">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input style="border: 1px solid black;" class="form-control" type="text" name="wc" placeholder="white blood cell ">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <input style="border: 1px solid black;" class="form-control" type="text" name="bu" placeholder="blood urea">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input style="border: 1px solid black;" class="form-control" type="text" name="bgr" placeholder="blood glucose random">
                        </div>
                    </div>
               
                    <div class="col-md-6">
                        <div class="form-group">
                            <input style="border: 1px solid black;" class="form-control" type="text" name="sc" placeholder="serum creatinine">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input style="border: 1px solid black;" class="form-control" type="text" name="pcv" placeholder="packed cell volume">
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <input style="border: 1px solid black;" class="form-control" type="text" name="al" placeholder="albumin">
                        </div>
                    </div> 
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input style="border: 1px solid black;" class="form-control" type="text" name="hm" placeholder="haemoglobin">
                        </div>
                    </div>
                    <div class="col-md-6">
                            <div class="form-group">
                                <input style="border: 1px solid black;" class="form-control" type="text" name="age" placeholder="age">
                            </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input style="border: 1px solid black;" class="form-control" type="text" name="su" placeholder="sugar">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <input style="border: 1px solid black;" class="form-control" type="text" name="htn" placeholder="hypertension">
                        </div>
                    </div>
                </div>
            </form>
         
            </div>
            
              
                  <div class="row">    
                    <input type="submit" class="btn btn-info btn-block "  value="Predict">
                      </div>
           
            
            
        </div>
     
        
    </div>
</div> <br>


{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}

{% block content %}
<div class="wrapper fadeInDown">
    <div id="formContent">
      <!-- Tabs Titles -->
  
      <!-- Icon -->
      <div class="fadeIn first">
        <img src="static\logo1.ico" id='icon' alt="User Icon" />
      </div>
  
      <!-- Login Form -->
      <form method="POST">
        <input type="email" id="email" class="fadeIn second" name="email" placeholder="Enter Email">
        <input type="password" id="password" class="fadeIn third" name="password"  placeholder="Enter Password">
        <input type="submit" class="fadeIn fourth" value="Log In">
      </form>
  
      <!-- Remind Passowrd -->
      <div id="formFooter">
        <a class="underlineHover" href="#">Forgot Password?</a>
      </div>
  
    </div>
  </div>

{% endblock %}

website/templates/predict.html
{% extends 'base.html' %}  {% block title %}Prediction {% endblock %}
{% block content %}
<div class="row d-flex justify-content-center"  style="margin-bottom: 477px;">
    <div class="col-md-8">
        {% if pred == 1 %}
            <div class="jumbotron ">
                <h1 class="display-4">You have a Kidney Disease !</h1>
                <p class="lead">Please Consult the Doctor Immideately. It was too risky without consultation. Make sure of health in your diet.</p>
                <hr class="my-4">
                <p>Proper Doctor Consultation Needed.</p>
                <p class="lead">
                    <a class="btn btn-primary btn-lg" href="https://www.who.int/" role="button">Learn more</a>
                </p>
            </div>
        {% else %}
            <div class="jumbotron">
                <h1 class="display-4">Great! You are Healthy</h1>
                <p class="lead">You are Absolutely Alright ! There is no Marks for Kidney Disease. Enjoy you life with full of Happiness.</p>
                <hr class="my-4">
                <p>Be careful at your health. Nothing is important than your health.</p>
                <p class="lead">
                    <a class="btn btn-primary btn-lg" href="https://www.who.int/" role="button">Learn more</a>
                </p>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4"><a href="{{ url_for('views.home') }}" class="btn btn-block btn-primary">Back to Home</a></div>
            <div class="col-md-4"></div>
        </div>
    </div>

</div>


{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %}

{% block content %}
<div class="wrapper fadeInDown">
    <div id="formContent">
      <!-- Tabs Titles -->
  
      <!-- Icon -->
      <div class="fadeIn first">
        <img src="static\logo1.ico" id="icon" alt="User Icon" />
      </div>
  
      <!-- Sign Up  Form -->
      <form method="POST">
        <input type="email" class="fadeIn second"  id="email" name="email" placeholder="Enter Email"/>
        <input type="text" class="fadeIn third"  id="firstName" name="firstName" placeholder="Enter First Name"/>
        <input type="password" id="password1" class="fadeIn second" name="password1" placeholder="Password">
        <input type="password" id="password2" class="fadeIn third" name="password2" placeholder="Confirm Password">
        <input type="submit" class="fadeIn fourth" value="Submit">
      </form>

  
    </div>
  </div>
{% endblock %}